language: node_js
node_js:
  - "node"
branches:
  only:
    - master
before_script:
  - npm install -g firebase-tools
script:
  echo “Deploy!!”
after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive